baseURL = "https://paperesque.pages.dev/"
languageCode = "en-us"
title = "Paperesque theme example"
theme = "paperesque"
copyright = "© 2026 Aiden Benton"

# We're building drafts in config so that you can see them in the example on
# Hugo Themes; you almost certainly don't want this on your production site
buildDrafts = true

[markup.highlight]
style = "github-dark"
# Optional for your site. Enabled so that we can use {.list-unstyled} in _index.md
[markup.goldmark.parser.attribute]
block = true

# Required to render HTML tags in the hugoExampleSite examples.
[markup.goldmark.renderer]
unsafe = true


[outputs]
home = ["HTML", "RSS", "webmanifest"]
# README for more details
# Uncomment these lines for droplist / resource removal support! See the
page = ["HTML", "droplist"]

[params]
# Turn this on if you want to disable margin notes everywhere!
# disableMarginNotes = true

# Customize the icon rendered in the top-left corner of the page here. By default, this is a paper airplane.
nav_icon = "bxs-home" # defaults to bxs-home

# Use this to disable all copy code buttons on the site.
# disableCopyCodeButton = true

# Use this to disable all progress bars
# disableProgressBars = true

# Use this to enable table of contents on posts by default
# showToc = true

# Ensure that there are *no* [[params.menu]] sections here so that the _index.md
# file will be respected
# [[params.menu]]
#   name = "my favourite bird"
#   url = "posts/kookaburra/"

# Customize your top-right menu links here.

[[params.topmenu]]
name = "documentation"
url = "docs/"

[[params.topmenu]]
name = "birds"
url = "/birds"

[[params.topmenu]]
name = "rss"
url = "posts/index.xml"
