name = "Paperesque"
license = "MIT"
licenselink = "https://github.com/intothebeans/paperesque/blob/mainline/LICENSE.md"
description = "A unique theme for personal websites."
homepage = "https://paperesque.pages.dev/"
tags = ["blog", "personal", "light", "responsive", "dark"]
features = [
    "responsive",
    "margin notes",
    "resource processing",
    "draft highlighting",
    "abcjs support",
    "custom alerts",
]
min_version = "0.147.3"

[author]
name = "intothebeans"
homepage = "https://github.com/intothebeans"
